// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: common_def.proto

package pb_code

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 匹配到的对方玩家信息
type MatchTarget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"` // 玩家id
}

func (x *MatchTarget) Reset() {
	*x = MatchTarget{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_def_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchTarget) ProtoMessage() {}

func (x *MatchTarget) ProtoReflect() protoreflect.Message {
	mi := &file_common_def_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchTarget.ProtoReflect.Descriptor instead.
func (*MatchTarget) Descriptor() ([]byte, []int) {
	return file_common_def_proto_rawDescGZIP(), []int{0}
}

func (x *MatchTarget) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

// 战斗房间内的对方玩家信息
type RoomTarget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"` // 玩家id
}

func (x *RoomTarget) Reset() {
	*x = RoomTarget{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_def_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomTarget) ProtoMessage() {}

func (x *RoomTarget) ProtoReflect() protoreflect.Message {
	mi := &file_common_def_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomTarget.ProtoReflect.Descriptor instead.
func (*RoomTarget) Descriptor() ([]byte, []int) {
	return file_common_def_proto_rawDescGZIP(), []int{1}
}

func (x *RoomTarget) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

var File_common_def_proto protoreflect.FileDescriptor

var file_common_def_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x64, 0x65, 0x66, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x1f, 0x0a, 0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x1e, 0x0a, 0x0a, 0x52, 0x6f, 0x6f, 0x6d, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2e, 0x2f, 0x70, 0x62,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x3b, 0x70, 0x62, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_def_proto_rawDescOnce sync.Once
	file_common_def_proto_rawDescData = file_common_def_proto_rawDesc
)

func file_common_def_proto_rawDescGZIP() []byte {
	file_common_def_proto_rawDescOnce.Do(func() {
		file_common_def_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_def_proto_rawDescData)
	})
	return file_common_def_proto_rawDescData
}

var file_common_def_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_def_proto_goTypes = []interface{}{
	(*MatchTarget)(nil), // 0: pb.MatchTarget
	(*RoomTarget)(nil),  // 1: pb.RoomTarget
}
var file_common_def_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_def_proto_init() }
func file_common_def_proto_init() {
	if File_common_def_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_def_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchTarget); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_def_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomTarget); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_def_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_def_proto_goTypes,
		DependencyIndexes: file_common_def_proto_depIdxs,
		MessageInfos:      file_common_def_proto_msgTypes,
	}.Build()
	File_common_def_proto = out.File
	file_common_def_proto_rawDesc = nil
	file_common_def_proto_goTypes = nil
	file_common_def_proto_depIdxs = nil
}
