// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: msg_id.proto

package pb_code

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息id
type MsgId int32

const (
	MsgId_HeartBeat     MsgId = 0 // 心跳
	MsgId_Login         MsgId = 1 // 登录消息
	MsgId_Match         MsgId = 2 // 匹配消息
	MsgId_MatchResult   MsgId = 3 // 匹配结果消息
	MsgId_EnterRoom     MsgId = 4 // 进入房间消息
	MsgId_UserEnterRoom MsgId = 5 // 用户进入房间消息
)

// Enum value maps for MsgId.
var (
	MsgId_name = map[int32]string{
		0: "HeartBeat",
		1: "Login",
		2: "Match",
		3: "MatchResult",
		4: "EnterRoom",
		5: "UserEnterRoom",
	}
	MsgId_value = map[string]int32{
		"HeartBeat":     0,
		"Login":         1,
		"Match":         2,
		"MatchResult":   3,
		"EnterRoom":     4,
		"UserEnterRoom": 5,
	}
)

func (x MsgId) Enum() *MsgId {
	p := new(MsgId)
	*p = x
	return p
}

func (x MsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_id_proto_enumTypes[0].Descriptor()
}

func (MsgId) Type() protoreflect.EnumType {
	return &file_msg_id_proto_enumTypes[0]
}

func (x MsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgId.Descriptor instead.
func (MsgId) EnumDescriptor() ([]byte, []int) {
	return file_msg_id_proto_rawDescGZIP(), []int{0}
}

var File_msg_id_proto protoreflect.FileDescriptor

var file_msg_id_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x2a, 0x5f, 0x0a, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x0d, 0x0a, 0x09, 0x48,
	0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x10, 0x02,
	0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x10,
	0x03, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x10, 0x04,
	0x12, 0x11, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6f,
	0x6d, 0x10, 0x05, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x3b, 0x70, 0x62, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_msg_id_proto_rawDescOnce sync.Once
	file_msg_id_proto_rawDescData = file_msg_id_proto_rawDesc
)

func file_msg_id_proto_rawDescGZIP() []byte {
	file_msg_id_proto_rawDescOnce.Do(func() {
		file_msg_id_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_id_proto_rawDescData)
	})
	return file_msg_id_proto_rawDescData
}

var file_msg_id_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msg_id_proto_goTypes = []interface{}{
	(MsgId)(0), // 0: pb.MsgId
}
var file_msg_id_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msg_id_proto_init() }
func file_msg_id_proto_init() {
	if File_msg_id_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_id_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_id_proto_goTypes,
		DependencyIndexes: file_msg_id_proto_depIdxs,
		EnumInfos:         file_msg_id_proto_enumTypes,
	}.Build()
	File_msg_id_proto = out.File
	file_msg_id_proto_rawDesc = nil
	file_msg_id_proto_goTypes = nil
	file_msg_id_proto_depIdxs = nil
}
