// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: res_code.proto

package pb_code

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用返回码 客户端用作逻辑判断 统一错误提示
type ResCode int32

const (
	ResCode_Success ResCode = 0 // 成功
	ResCode_Fail    ResCode = 1 // 失败
)

// Enum value maps for ResCode.
var (
	ResCode_name = map[int32]string{
		0: "Success",
		1: "Fail",
	}
	ResCode_value = map[string]int32{
		"Success": 0,
		"Fail":    1,
	}
)

func (x ResCode) Enum() *ResCode {
	p := new(ResCode)
	*p = x
	return p
}

func (x ResCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResCode) Descriptor() protoreflect.EnumDescriptor {
	return file_res_code_proto_enumTypes[0].Descriptor()
}

func (ResCode) Type() protoreflect.EnumType {
	return &file_res_code_proto_enumTypes[0]
}

func (x ResCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResCode.Descriptor instead.
func (ResCode) EnumDescriptor() ([]byte, []int) {
	return file_res_code_proto_rawDescGZIP(), []int{0}
}

var File_res_code_proto protoreflect.FileDescriptor

var file_res_code_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x65, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x2a, 0x20, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04,
	0x46, 0x61, 0x69, 0x6c, 0x10, 0x01, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x3b, 0x70, 0x62, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_res_code_proto_rawDescOnce sync.Once
	file_res_code_proto_rawDescData = file_res_code_proto_rawDesc
)

func file_res_code_proto_rawDescGZIP() []byte {
	file_res_code_proto_rawDescOnce.Do(func() {
		file_res_code_proto_rawDescData = protoimpl.X.CompressGZIP(file_res_code_proto_rawDescData)
	})
	return file_res_code_proto_rawDescData
}

var file_res_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_res_code_proto_goTypes = []interface{}{
	(ResCode)(0), // 0: pb.ResCode
}
var file_res_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_res_code_proto_init() }
func file_res_code_proto_init() {
	if File_res_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_res_code_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_res_code_proto_goTypes,
		DependencyIndexes: file_res_code_proto_depIdxs,
		EnumInfos:         file_res_code_proto_enumTypes,
	}.Build()
	File_res_code_proto = out.File
	file_res_code_proto_rawDesc = nil
	file_res_code_proto_goTypes = nil
	file_res_code_proto_depIdxs = nil
}
